language: node_js
node_js:
  - 15.12.0
branch: master
cache:
  directories:
    - node_modules
before_install:
  - export TZ='Asia/Shanghai' # 设置时区
install:
  - yarn install
after_script:
  - ./deploy.sh
branches:
  only:
  - master # 触发持续集成的分支
